In [1]:
#modul yang digunakan
import matplotlib.pyplot as plt
import mesa_reader as ms
import pandas as pd
import math

In [2]:
#variabel untuk bintang bermassa sedang tanpa overshooting (NOOV)
h_2m = ms.MesaData('../LOGS/NOOV STARS/2Msun(NOOV)/trimmed_history.data')
h_3m = ms.MesaData('../LOGS/NOOV STARS/3Msun(NOOV)/trimmed_history.data')
h_4m = ms.MesaData('../LOGS/NOOV STARS/4Msun(NOOV)/trimmed_history.data')
h_5m = ms.MesaData('../LOGS/NOOV STARS/5Msun(NOOV)/trimmed_history.data')
h_6m = ms.MesaData('../LOGS/NOOV STARS/6Msun(NOOV)/trimmed_history.data')
h_7m = ms.MesaData('../LOGS/NOOV STARS/7Msun(NOOV)/trimmed_history.data')
h_8m = ms.MesaData('../LOGS/NOOV STARS/8Msun(NOOV)/trimmed_history.data')

h_2m_mass = math.ceil(max(list(h_2m.data('star_mass'))))
h_3m_mass = math.ceil(max(list(h_3m.data('star_mass'))))
h_4m_mass = math.ceil(max(list(h_4m.data('star_mass'))))
h_5m_mass = math.ceil(max(list(h_5m.data('star_mass'))))
h_6m_mass = math.ceil(max(list(h_6m.data('star_mass'))))
h_7m_mass = math.ceil(max(list(h_7m.data('star_mass'))))
h_8m_mass = math.ceil(max(list(h_8m.data('star_mass'))))


#variabel untuk bintang bermassa sedang dengan overshooting (OV)
h_2m_OV = ms.MesaData('../LOGS/OV STARS/2Msun(OV)/trimmed_history.data')
h_3m_OV = ms.MesaData('../LOGS/OV STARS/3Msun(OV)/trimmed_history.data')
h_4m_OV = ms.MesaData('../LOGS/OV STARS/4Msun(OV)/trimmed_history.data')
h_5m_OV = ms.MesaData('../LOGS/OV STARS/5Msun(OV)/trimmed_history.data')
h_6m_OV = ms.MesaData('../LOGS/OV STARS/6Msun(OV)/trimmed_history.data')
h_7m_OV = ms.MesaData('../LOGS/OV STARS/7Msun(OV)/trimmed_history.data')
h_8m_OV = ms.MesaData('../LOGS/OV STARS/8Msun(OV)/trimmed_history.data')

h_2m_OV_mass = math.ceil(max(list(h_2m_OV.data('star_mass'))))
h_3m_OV_mass = math.ceil(max(list(h_3m_OV.data('star_mass'))))
h_4m_OV_mass = math.ceil(max(list(h_4m_OV.data('star_mass'))))
h_5m_OV_mass = math.ceil(max(list(h_5m_OV.data('star_mass'))))
h_6m_OV_mass = math.ceil(max(list(h_6m_OV.data('star_mass'))))
h_7m_OV_mass = math.ceil(max(list(h_7m_OV.data('star_mass'))))
h_8m_OV_mass = math.ceil(max(list(h_8m_OV.data('star_mass'))))

In [3]:
#deklarasi fungsi-fungsi yang digunakan

#fungsi untuk menentukan umur pada fase ZAMS bintang (dimulai pada awal pembakaran hidrogen)
def find_ZAMS_age(var):
    for i in range(1,len(var.star_age)):
         if var.data('center_h1')[i] == 0.7:
            return var.data("star_age")[i]

#fungsi untuk menentukan umur pada awal fase RGB bintang (dimulai saat penghabisan inti hidrogen)
def find_RGB_age(var):
    for i in range(1,len(var.star_age)):
         if var.data('center_h1')[i] == 0:
            return var.data("star_age")[i]

        
#fungsi untuk menentukan umur pada fase awal AGB bintang (dimulai saat penghabisan inti helium)
def find_AGB_age(var):
    for i in range(1,len(var.star_age)):
         if var.data('center_he4')[i] <= 1e-4:
            return var.data("star_age")[i]


#fungsi untuk menentukan masa hidup bintang pada fase DU (dari ZAMS hingga awal RGB)
def MS_lifetime(var):
    return find_RGB_age(var)-find_ZAMS_age(var)



##########################################################################################



#fungsi untuk menentukan kelimpahan inti karbon pada akhir masa hidup bintang 
def carbon_end(var):
    return(float(var.data('center_c12')[-1]))


#fungsi untuk menentukan kelimpahan inti oksigen pada akhir masa hidup bintang 
def oxygen_end(var):
    return(float(var.data('center_o16')[-1]))

#fungsi untuk menentukan kelimpahan inti neon pada akhir masa hidup bintang 
def neon_end(var):
    return(float(var.data('center_ne20')[-1]))



##########################################################################################



####################################### TEST RUN #########################################


# print(neon_end(h_2m)/carbon_end(h_2m))


# for i in range(1,len(h_2m.star_age)):
#     print(h_2m.data('center_c12')[-1])


# print(MS_lifetime(h_2m))

# print(find_RGB_age(h_2m)
# print(find_RGB_age(h_2m_OV))

# print(find_ZAMS_age(h_2m))

# print(find_AGB_age(h_2m))
# print(find_AGB_age(h_2m_OV))

In [4]:
#pembuatan tabel umur pada saat fase X untuk bintang NOOV

#list untuk massa bintang
massa_bintang = [
    h_2m_mass, h_3m_mass, h_4m_mass, h_5m_mass, h_6m_mass, h_7m_mass, h_8m_mass
]

#list untuk data bintang
data_bintang = [
    h_2m, h_3m, h_4m, h_5m, h_6m, h_7m, h_8m
]



#masukkan tabel
masukan_tabel_umur_faseX_NOOV= {
    r'Massa Bintang ($M_{\odot,NOOV}$)': [massa_bintang[i] for i in range(len(massa_bintang))],
    'ZAMS (tahun)': ["%.2e" % find_ZAMS_age(data_bintang[i]) for i in range(len(massa_bintang))],
    'RGB (tahun)': ["%.2e" % find_RGB_age(data_bintang[i]) for i in range(len(massa_bintang))],
    'AGB (tahun)': ["%.2e" % find_AGB_age(data_bintang[i]) for i in range(len(massa_bintang))],
    'Masa Hidup Fase DU (tahun)': ["%.2e" % MS_lifetime(data_bintang[i]) for i in range(len(massa_bintang))],   
}


tabel_umur_faseX_NOOV = pd.DataFrame(masukan_tabel_umur_faseX_NOOV)
display(tabel_umur_faseX_NOOV)

,"Massa Bintang ($M_{\odot,NOOV}$)",ZAMS (tahun),RGB (tahun),AGB (tahun),Masa Hidup Fase DU (tahun)
0,2,7.67e+04,9.71e+08,1.18e+09,9.71e+08
1,3,6.36e+04,3.15e+08,4.23e+08,3.15e+08
2,4,3.31e+04,1.48e+08,1.82e+08,1.47e+08
3,5,3.16e+04,8.46e+07,1.01e+08,8.45e+07
4,6,2.96e+04,5.50e+07,6.48e+07,5.50e+07
5,7,2.75e+04,3.92e+07,4.55e+07,3.92e+07
6,8,2.40e+04,2.99e+07,3.42e+07,2.99e+07

In [5]:
#pembuatan tabel kelimpahan unsur inti bintang pada akhir masa hidupnya untuk bintang NOOV

#masukkan tabel
masukan_tabel_kelimpahan_NOOV = {
    r'Massa Bintang ($M_{\odot,NOOV}$)': [massa_bintang[i] for i in range(len(massa_bintang))],
    r'X$_{c}$($^{12}$C)': ["%.3f" %carbon_end(data_bintang[i]) for i in range(len(massa_bintang))],
    r'X$_{c}$($^{16}$O)': ["%.3f" % oxygen_end(data_bintang[i]) for i in range(len(massa_bintang))],
    r'X$_{c}$($^{20}$Ne)': ["%.4f" % neon_end(data_bintang[i]) for i in range(len(massa_bintang))],
    r'$^{12}$C:$^{16}$O:$^{20}$Ne': [f'{"%.0f" % (carbon_end(data_bintang[i])/carbon_end(data_bintang[i]))} : {"%.2f" % (oxygen_end(data_bintang[i])/carbon_end(data_bintang[i]))} : {"%.3f" % (neon_end(data_bintang[i])/carbon_end(data_bintang[i]))}' for i in range(len(massa_bintang))
              ]
}

tabel_kelimpahan_NOOV = pd.DataFrame(masukan_tabel_kelimpahan_NOOV)
display(tabel_kelimpahan_NOOV)

,"Massa Bintang ($M_{\odot,NOOV}$)",X$_{c}$($^{12}$C),X$_{c}$($^{16}$O),X$_{c}$($^{20}$Ne),$^{12}$C:$^{16}$O:$^{20}$Ne
0,2,0.298,0.676,0.0023,1 : 2.27 : 0.008
1,3,0.307,0.666,0.0023,1 : 2.17 : 0.007
2,4,0.388,0.586,0.0023,1 : 1.51 : 0.006
3,5,0.407,0.567,0.0023,1 : 1.39 : 0.006
4,6,0.416,0.557,0.0023,1 : 1.34 : 0.005
5,7,0.416,0.558,0.0023,1 : 1.34 : 0.005
6,8,0.411,0.562,0.0023,1 : 1.37 : 0.006

In [6]:
#pembuatan tabel umur pada saat fase X untuk bintang OV

#list untuk massa bintang
massa_bintang_OV = [
    h_2m_OV_mass, h_3m_OV_mass, h_4m_OV_mass, h_5m_OV_mass, h_6m_OV_mass, h_7m_OV_mass, h_8m_OV_mass
]

#list untuk data bintang
data_bintang_OV = [
    h_2m_OV, h_3m_OV, h_4m_OV, h_5m_OV, h_6m_OV, h_7m_OV, h_8m_OV
]



#masukkan tabel
masukan_tabel_umur_faseX_OV= {
    r'Massa Bintang ($M_{\odot,OV}$)': [massa_bintang_OV[i] for i in range(len(massa_bintang))],
    'ZAMS (tahun)': ["%.2e" % find_ZAMS_age(data_bintang_OV[i]) for i in range(len(massa_bintang))],
    'RGB (tahun)': ["%.2e" % find_RGB_age(data_bintang_OV[i]) for i in range(len(massa_bintang))],
    'AGB (tahun)': ["%.2e" % find_AGB_age(data_bintang_OV[i]) for i in range(len(massa_bintang))],
    'Masa Hidup Fase DU (tahun)': ["%.2e" % MS_lifetime(data_bintang_OV[i]) for i in range(len(massa_bintang))],  
}

tabel_umur_faseX_OV = pd.DataFrame(masukan_tabel_umur_faseX_OV)
display(tabel_umur_faseX_OV)

,"Massa Bintang ($M_{\odot,OV}$)",ZAMS (tahun),RGB (tahun),AGB (tahun),Masa Hidup Fase DU (tahun)
0,2,7.63e+04,1.11e+09,1.32e+09,1.11e+09
1,3,6.35e+04,3.68e+08,4.44e+08,3.67e+08
2,4,3.31e+04,1.73e+08,1.98e+08,1.73e+08
3,5,3.16e+04,9.90e+07,1.12e+08,9.89e+07
4,6,2.95e+04,6.45e+07,7.23e+07,6.45e+07
5,7,2.75e+04,4.61e+07,5.12e+07,4.61e+07
6,8,2.40e+04,3.49e+07,3.87e+07,3.49e+07

In [7]:
#pembuatan kelimpahan unsur inti bintang pada akhir masa hidupnya untuk bintang OV

#masukkan tabel
masukan_tabel_kelimpahan_OV = {
    r'Massa Bintang ($M_{\odot,OV}$)': [massa_bintang_OV[i] for i in range(len(massa_bintang))],
    r'X$_{c}$($^{12}$C)': ["%.3f" % carbon_end(data_bintang_OV[i]) for i in range(len(massa_bintang))],
    r'X$_{c}$($^{16}$O)': ["%.3f" % oxygen_end(data_bintang_OV[i]) for i in range(len(massa_bintang))],
    r'X$_{c}$($^{20}$Ne)': ["%.4f" % neon_end(data_bintang_OV[i]) for i in range(len(massa_bintang))],
    r'$^{12}$C:$^{16}$O:$^{20}$Ne': [f'{"%.0f" % (carbon_end(data_bintang_OV[i])/carbon_end(data_bintang_OV[i]))} : {"%.2f" % (oxygen_end(data_bintang_OV[i])/carbon_end(data_bintang_OV[i]))} : {"%.3f" % (neon_end(data_bintang_OV[i])/carbon_end(data_bintang_OV[i]))}' for i in range(len(massa_bintang_OV))
              ]
}

tabel_kelimpahan_OV = pd.DataFrame(masukan_tabel_kelimpahan_OV)
display(tabel_kelimpahan_OV)

,"Massa Bintang ($M_{\odot,OV}$)",X$_{c}$($^{12}$C),X$_{c}$($^{16}$O),X$_{c}$($^{20}$Ne),$^{12}$C:$^{16}$O:$^{20}$Ne
0,2,0.321,0.653,0.0023,1 : 2.03 : 0.007
1,3,0.355,0.618,0.0023,1 : 1.74 : 0.006
2,4,0.417,0.556,0.0023,1 : 1.33 : 0.005
3,5,0.427,0.546,0.0023,1 : 1.28 : 0.005
4,6,0.423,0.551,0.0023,1 : 1.30 : 0.005
5,7,0.412,0.561,0.0023,1 : 1.36 : 0.006
6,8,0.165,0.527,0.2220,1 : 3.20 : 1.346

In [8]:
#pembuatan tabel umur bintang pada akhir masa hidupnya untuk bintang OV dan bintang NOOV

#list untuk menampung data umur bintang pada akhir masa hidupnya
umur_bintang = []
umur_bintang_OV = []

for i in range(len(data_bintang)):
    umur_bintang.append(data_bintang[i].data('star_age')[-1])
    umur_bintang_OV.append(data_bintang_OV[i].data('star_age')[-1])
    
#masukkan tabel
masukan_tabel_umur_akhir_bintang = {
    r'Massa Bintang ($M_{\odot}$)' : [massa_bintang[i] for i in range(len(massa_bintang))]  + [massa_bintang_OV[i] for i in range(len(massa_bintang))],
    '' : [r'$NO OV$']*7 + [r'$OV$']*7,
    'Umur Bintang (tahun)' : ['%.2e' %umur_bintang[i] for i in range(len(umur_bintang))] + ['%.2e' % umur_bintang_OV[i] for i in range(len(umur_bintang))],
}
tabel_umur_akhir_bintang = pd.DataFrame(masukan_tabel_umur_akhir_bintang)
tabel_umur_akhir_bintang_CLEANED =  pd.pivot(tabel_umur_akhir_bintang, index=r'Massa Bintang ($M_{\odot}$)', columns='', values=['Umur Bintang (tahun)'])

display(tabel_umur_akhir_bintang_CLEANED)

                            Umur Bintang (tahun)
                                         $NO OV$      $OV$
Massa Bintang ($M_{\odot}$)
2                                       1.21e+09  1.36e+09
3                                       4.53e+08  4.58e+08
4                                       1.92e+08  2.03e+08
5                                       1.06e+08  1.14e+08
6                                       6.77e+07  7.31e+07
7                                       4.73e+07  5.16e+07
8                                       3.54e+07  3.89e+07